sudo: false

language: minimal

services:
  - docker

script:
  - pwd
  - ls -l
  - docker pull raz0red/devkitppc
  - docker run -v $(pwd)/wiicolem:/source raz0red/devkitppc  bash -c 'cd /source; make'
