name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: pwd
    - run: ls -l
    - run: docker pull raz0red/devkitppc
    - run: docker run -v $(pwd)/wiicolem:/source raz0red/devkitppc make -C $(pwd)/wiicolem
